

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_FAIL = 'CART_FAIL';
export const CART_ADD_SHIPPING_ADDRESS = 'CART_ADD_SHIPPING_ADDRESS';
export const CART_ADD_PAYMENT_METHOD = 'CART_ADD_PAYMENT_METHOD';


export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'