export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS';
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL';
export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST';

export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';
export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_FAIL = 'CART_FAIL';
