export const ISSUES_LIST_SUCCESS = 'ISSUES_LIST_SUCCESS';
export const ISSUES_LIST_FAIL = 'ISSUES_LIST_FAIL';
export const ISSUES_LIST_REQUEST = 'ISSUES_LIST_REQUEST';

export const ISSUES_DETAILS_SUCCESS = 'ISSUES_DETAILS_SUCCESS';
export const ISSUES_DETAILS_FAIL = 'ISSUES_DETAILS_FAIL';
export const ISSUES_DETAILS_REQUEST = 'ISSUES_DETAILS_REQUEST';

export const ISSUE_DELETE_REQUEST = 'ISSUE_DELETE_REQUEST';
export const ISSUE_DELETE_SUCCESS = 'ISSUE_DELETE_SUCCESS';
export const ISSUE_DELETE_FAIL = 'ISSUE_DELETE_FAIL'

export const ISSUE_UPDATE_REQUEST = 'ISSUE_UPDATE_REQUEST';
export const ISSUE_UPDATE_SUCCESS = 'ISSUE_UPDATE_SUCCESS';
export const ISSUE_UPDATE_FAIL = 'ISSUE_UPDATE_FAIL'
export const ISSUE_UPDATE_RESET = 'ISSUE_UPDATE_RESET'

export const ISSUE_DETAILS_REQUEST = 'ISSUE_DETAILS_REQUEST';
export const ISSUE_DETAILS_SUCCESS = 'ISSUE_DETAILS_SUCCESS';
export const ISSUE_DETAILS_FAIL = 'ISSUE_DETAILS_FAIL';

export const ISSUE_DETAILS_UPDATE_REQUEST = 'ISSUE_DETAILS_UPDATE_REQUEST';
export const ISSUE_DETAILS_UPDATE_SUCCESS = 'ISSUE_DETAILS_UPDATE_SUCCESS';
export const ISSUE_DETAILS_UPDATE_FAIL = 'ISSUE_DETAILS_UPDATE_FAIL';
export const ISSUE_DETAILS_UPDATE_RESET = 'ISSUE_DETAILS_UPDATE_RESET';

export const ISSUE_CREATE_REQUEST = 'ISSUE_CREATE_REQUEST';
export const ISSUE_CREATE_SUCCESS = 'ISSUE_CREATE_SUCCESS';
export const ISSUE_CREATE_FAIL = 'ISSUE_CREATE_FAIL'
export const ISSUE_CREATE_RESET = 'ISSUE_CREATE_RESET'

export const ISSUE_INIT_REQUEST = 'ISSUE_INIT_REQUEST';
export const ISSUE_INIT_SUCCESS = 'ISSUE_INIT_SUCCESS';
export const ISSUE_INIT_FAIL = 'ISSUE_INIT_FAIL'
export const ISSUE_INIT_RESET = 'ISSUE_INIT_RESET'

export const ISSUE_TOP_REQUEST = 'ISSUE_TOP_REQUEST';
export const ISSUE_TOP_SUCCESS = 'ISSUE_TOP_SUCCESS';
export const ISSUE_TOP_FAIL = 'ISSUE_TOP_FAIL'
